### ISSUE TITLE
Reduce size of project images

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#164]
project images for projects are often quite massive (somtimes >500K) and this is bad for page performance and b/w usage.

Especially a problem on project listing page (cf #46) as we load all project images

**Comment by rgrp** [comment]
@mchelen @loleg what's the status of this issue? Is it WONTFIX or do we want to do more to close this out?

**Comment by loleg** [comment]
@rgrp I'm fine with pulling in the patch from @mchelen - as long as we raise a separate issue to simplify the build steps, e.g. revisit the idea of using jekyll-picture-tag in the future.

**Comment by rgrp** [comment]
@loleg my thing is i'd a bit concerned about having to run a build to do a deploy (will the patch require that going forward)?

**Comment by mchelen** [comment]
@rgrp Build is only required when you want to optimize the images. So for example when adding a new project with an external image URL, it will initially use the external URL. Then once someone runs build, it will fetch the image, optimize it, and use this new local & optimized version instead of the external URL.
I can't think of any simpler way to optimize images when they are external URLs.

@loleg jekyll-picture-tag is great but it will still need a prior step to fetch external images. Maybe the best way to handle that in the future is to require contributors to add the image directly to the repo, instead of using external URLs in the first place.

**Comment by rgrp** [comment]
@mchelen @loleg. Awesome let's get this in :-)
