### ISSUE TITLE
Update population data

### ISSUE THREAD

**Issue by ivarref** [okfn/okfn.github.com#495]
Hi, and thanks for some fine data.

It seems that the [okfn population figures](http://data.okfn.org/data/core/population) stops in 2014, but the original [World Bank source](http://data.worldbank.org/indicator/SP.POP.TOTL)  has data for 2015.

Would it be possible to update this?

**Comment by danfowler** [comment]
Hello @ivarref thanks for raising this issue!  The data on data.okfn.org are Data Packages based on data stored in GitHub repos the [Frictionless Data specs](http://specs.frictionlessdata.io/).  The source repo for these datasets is here: https://github.com/datasets/population

Because it is based on GitHub, anyone can update using the provided script and submitting a PR.  I am [updating](https://github.com/datasets/population/pull/6).

If you are working with pulling in CSV data into Clojure, it would be interesting to talk about what your challenges are.  We have a Gitter channel here: https://gitter.im/frictionlessdata/chat

Closing this issue as I have reopened it in a more relevant repo: https://github.com/datasets/population/issues/7
